#!/usr/bin/env php
<?php

define('APP_START', microtime(true));


require 'vendor/autoload.php';
require 'app/Core/Console.php';

use App\Core\Console;

$console = new Console();
$console->run($argv);

// chmod +x console

?>
